# Generated by Django 2.0.7 on 2018-07-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesdbapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
